config/routes.rb
Rails.application.routes.draw do
  root "users#new"
  get  '/new',      to: 'static_pages#new'
  get  '/about',    to: 'static_pages#about'
  get  '/contact',  to: 'static_pages#contact'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get  "/search",   to: "microposts#index"
  get  "/detail",   to: "microposts#detail"
  get '/auth/:provider/callback',    to: 'users#facebook_login',      as: :auth_callback
  get '/auth/failure',               to: 'users#auth_failure',        as: :auth_failure
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy] do
    resources :comments
  end
  resources :relationships,       only: [:create, :destroy]
  resources :likes,               only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :username,  presence: true, length: { maximum: 50 }, on: :facebook_login
  validates :fullname,  presence: true, length: { maximum: 50 }, on: :facebook_login
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }, on: :facebook_login
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true, on: :facebook_login

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # facebookログイン
  def self.from_omniauth(auth)
    # facebookに登録しているemailを、データベースから探す
    user = User.where('email = ?', auth.info.email).first
    if user.blank?
      user = User.new
    end
    user.uid = auth.uid
    user.fullname = auth.info.name
    user.username = auth.info.name
    user.email = auth.info.email
    user.image = auth.info.image
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user
  end

  # タイムラインを返す
  def feed
    following_ids = "SELECT followed_id FROM relationships
                   WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                   OR user_id = :user_id", user_id: id)
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  # ユーザーの一覧を取得
  def index
    @users = User.paginate(page: params[:page])
  end

  # ユーザー固有のポストを取得
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  # 新規ユーザー作成ページを取得
  def new
    @user = User.new
  end

  # 新規ユーザーを作成
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Instagram!"
      redirect_to @user
    else
      render 'new'
    end
  end

  # facebookログイン
  def facebook_login
    @user  = User.from_omniauth(request.env["omniauth.auth"])
    result = @user.save(context: :facebook_login)
    if result
      log_in @user
      flash[:success] = "FACEBOOKでログインしました。"
      redirect_to @user
    else
      redirect_to auth_failure_path
    end
  end

  # 認証に失敗
  def auth_failure
    @user = User.new
    flash[:danger] = "ログインに失敗しました"
    render 'new'
  end

  # ユーザー情報編集ページを取得
  def edit
    @user = User.find(params[:id])
  end

  # ユーザー情報を更新
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  # ユーザー情報を削除
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  # フォローしているユーザーを表示
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  # フォローされているユーザーを表示
  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

  def user_params
    params.require(:user).permit(:username, :fullname, :email, :password,
                                 :password_confirmation)
  end

  # 正しいユーザーかどうか確認
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end

  # 管理者かどうか確認
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.fullname, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_myphoto.html.erb
  <span class="content">
    <div class= postimg>
    <%= gravatar_for micropost.user, size: 20 %>
    <h4><%= micropost.user.username %><h4>
    </div>
    <%= image_tag micropost.picture.url, :size =>'600x600' if micropost.picture? %>
    <%= micropost.content %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "プロフィール編集") %>
<h1>プロフィールを編集する</h1>

<div class="row">
  <div class="col-md-7 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.email_field :email, class: 'form-control', placeholder:  "メールアドレス" %>

      <%= f.text_field :fullname, class: 'form-control', placeholder:  "フルネーム" %>
      
      <%= f.text_field :username, class: 'form-control', placeholder:  "ユーザーネーム" %>

      <%= f.password_field :password, class: 'form-control', placeholder:  "パスワード" %>

      <%= f.password_field :password_confirmation, class: 'form-control', placeholder:  "パスワード確認" %>

      <%= f.submit "確定する", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">プロフィール画像を変更</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.fullname, user %>
      <% if current_user.admin? %>
       | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= link_to image_tag("instalogo2.png", alt: "insta logo"),root_path %>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
    
      <%= f.email_field :email, placeholder:  "メールアドレス", class: 'form-control' %>
    
      <%= f.text_field :fullname, placeholder:  "フルネーム", class: 'form-control'%>
      
      <%= f.text_field :username, placeholder:  "ユーザーネーム", class: 'form-control' %>

      <%= f.password_field :password, placeholder:  "パスワード", class: 'form-control' %>

      <%= f.password_field :password_confirmation, placeholder:  "パスワード確認", class: 'form-control' %>

      <%= f.submit "登録する", class: "btn btn-primary" %>
    <% end %>
    
    <p>アカウントをお持ちですか？<%= link_to "ログインする", login_path %></p>
  </div>
  <%= link_to image_tag("top.png", alt: "insta logo"),root_path %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.fullname) %>
<div class="row">
  <aside class="col-md-10 prof">
    </section>
    <section class="stats">
        <%= render 'shared/stats' %>
        <%= render 'follow_form' if logged_in? %>
    </section>
  </aside>
  <div class="col-md-13 mypics">
    <% if @user.microposts.any? %>
      <% @user.microposts.each do |micropost| %>
        <%= link_to detail_path(:id => micropost.id) do %>
          <%=image_tag micropost.picture%>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row mypictures">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.fullname %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
</div>