config/routes.rb
Rails.application.routes.draw do
  root "users#new"
  get  '/new',      to: 'static_pages#new'
  get  '/about',    to: 'static_pages#about'
  get  '/contact',  to: 'static_pages#contact'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get  "/search",   to: "microposts#index"
  get  "/detail",   to: "microposts#detail"
  get '/auth/:provider/callback',    to: 'users#facebook_login',      as: :auth_callback
  get '/auth/failure',               to: 'users#auth_failure',        as: :auth_failure
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy] do
    resources :comments
  end
  resources :relationships,       only: [:create, :destroy]
  resources :likes,               only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'%>
  </span>
  <div class="field">
    <%= f.text_area :content, placeholder: "コメントを入力"%>
  </div>
  <%= f.submit "投稿する", class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<span class= "round-img">
<%= link_to gravatar_for(current_user, size: 50), @user %>
</span>
<h1><%= @user.username %></h1>
<span><%= @user.fullname %></span>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>人をフォロー中
    </strong>
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      フォロワー<%= @user.followers.count %>人
    </strong>
  </a>
  <strong class="stat">
      投稿<%= @user.microposts.count %>件
  </strong>
</div>

app/views/shared/_user_info.html.erb
<span class= "round-img">
<%= link_to gravatar_for(current_user, size: 50), current_user %>
</span>
<h1><%= current_user.username %></h1>
<span><%= current_user.fullname %></span>