config/routes.rb
Rails.application.routes.draw do
  root "users#new"
  get  '/new',      to: 'static_pages#new'
  get  '/about',    to: 'static_pages#about'
  get  '/contact',  to: 'static_pages#contact'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get  "/search",   to: "microposts#index"
  get  "/detail",   to: "microposts#detail"
  get '/auth/:provider/callback',    to: 'users#facebook_login',      as: :auth_callback
  get '/auth/failure',               to: 'users#auth_failure',        as: :auth_failure
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy] do
    resources :comments
  end
  resources :relationships,       only: [:create, :destroy]
  resources :likes,               only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :iine_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, length: { maximum: 140 }
  validate  :picture_size

  # 投稿を検索する
  def self.search(search)
    if search
      Micropost.where(['content LIKE ?', "%#{search}%"])
    else
      Micropost.all
    end
  end

  # 投稿の詳細を探す
  def self.showdetail(imageid)
    Micropost.find(imageid)
  end

  # マイクロポストをいいねする
  def iine(user)
    likes.create(user_id: user.id)
  end

  # マイクロポストのいいねを解除する
  def uniine(user)
    likes.find_by(user_id: user.id).destroy
  end

  # 現在のユーザーがいいねしてたらtrueを返す
  def iine?(user)
    iine_users.include?(user)
  end

  private

  # アップロードされた画像のサイズをバリデーションする
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy

  # 新しい投稿を作成
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "posted!"
      redirect_to new_url
    else
      @feed_items = []
      render 'static_pages/new'
    end
  end

  # 投稿を削除
  def destroy
    @micropost.destroy
    flash[:success] = "deleted"
    redirect_to new_url
  end

  # 投稿を検索
  def index
    @microposts = Micropost.search(params[:search])
  end

  # 投稿の詳細を表示
  def detail
    @micropost = Micropost.showdetail(params[:id])
    @comment = Comment.new
    @comments = Comment.where(micropost_id: params[:id])
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :picture)
  end

  # 正しいユーザーでなければ初期ページへ遷移
  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<span class="content">
  <div class="micropost-head">
    <div class= "round-img">
      <%= gravatar_for micropost.user, size: 30 %>
    </div>
      <h5><%= micropost.user.username %></h5>
  </div>
  <%= link_to detail_path(:id => micropost.id) do %>
    <%= image_tag micropost.picture.url, :size =>'600x600' if micropost.picture? %>
  <% end %>
  <%= render "likes/like", micropost: micropost %>
</span>
  

app/views/microposts/detail.html.erb
<span class="content">
  <div class= postdetail>
  <%= gravatar_for @micropost.user, size: 20 %>
  <h4><%= @micropost.user.username %><h4>
  <%= image_tag @micropost.picture.url, :size =>'600x600' if @micropost.picture? %>
  <%= @micropost.content %>
  </div>
</span>
<div class="comment-list">
    <% @comments.each do |comment| %>
    <div class= "comment">
    <%= comment.user.fullname %>
    <%= comment.body %>
    <% if current_user?(@micropost.user) %>
      <%= link_to "delete", micropost_comment_path(@micropost, comment), method: :delete%>
    <% end %> 
    </div>
    <% end %>
</div>
<span class="timestamp">
  Posted <%= time_ago_in_words(@micropost.created_at) %> ago.
  <% if current_user?(@micropost.user) %>
    <%= link_to "delete", @micropost, method: :delete,
                                     data: { confirm: "You sure?" } %>
  <% end %>
</span>
<span class="comment-form">
  <%= form_for ([@micropost , @comment]) do |f| %>
    <div class="field">
      <%= f.text_field :body, placeholder: "コメントを追加..." %>
    </div>
    <%= f.submit "投稿", class: "hidden-btn" %>
  <% end %>
</span> 

app/views/microposts/index.html.erb
  <span class="content">
    <% @microposts.each do |micropost| %>
        <div class= postimg>
        <%= gravatar_for micropost.user, size: 20 %>
        <h4><%= micropost.user.username %><h4>
        </div>
        <%= image_tag micropost.picture.url, :size =>'600x600' if micropost.picture? %>
        <div>
        <%= micropost.content %>
        </div>
      </span>
      <span class="timestamp">
        Posted <%= time_ago_in_words(micropost.created_at) %> ago.
        <% if current_user?(micropost.user) %>
          <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
        <% end %>
    <% end %>
  </span>