config/routes.rb
Rails.application.routes.draw do
  root "users#new"
  get  '/new',      to: 'static_pages#new'
  get  '/about',    to: 'static_pages#about'
  get  '/contact',  to: 'static_pages#contact'
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get  "/search",   to: "microposts#index"
  get  "/detail",   to: "microposts#detail"
  get '/auth/:provider/callback',    to: 'users#facebook_login',      as: :auth_callback
  get '/auth/failure',               to: 'users#auth_failure',        as: :auth_failure
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy] do
    resources :comments
  end
  resources :relationships,       only: [:create, :destroy]
  resources :likes,               only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "インスタグラムについて",   about_path %>
    <%= link_to "サポート", contact_path %>
  </small>
  <nav>
    <ul>
      <li>© 2018 INSTAGRAM</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<% if logged_in? %>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-center">
        <li><%= link_to image_tag("instalogo.png", alt: "insta logo", class: "instalogo"),current_user %></li>
        <%= form_tag search_path, :method => 'get' do %> 
        <li class="input-group">
          <%= text_field_tag :search, params[:search], placeholder: "検索", class: "search-form" %>
          <span class="input-group-btn">
          <%= submit_tag "Search", :name => nil, class: "hidden-btn" %>
          </span>
        <% end %>
        </li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Timeline", new_path %></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
        </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>